FROM node:16.16.0 as build-stage
RUN mkdir -p /app
COPY . /app/
WORKDIR /app

RUN npm install
RUN npm run build
RUN npm run generate dist/

FROM nginx:stable-alpine as production-stage
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html


